name: MobHuntEvent
version: '${project.version}'
main: me.chrisx97.mobhuntevent.MobHuntEventPlugin
api-version: 1.19
authors: [ Chrisx97 ]
description: Mob hunt event
commands:
  mobhunt:
    description: mob hunt base command
    aliases: [mh, mhunt]